executors:
  node:
    docker:
      - image: circleci/node:12
    working_directory: ~/forge
  tester:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/forge
  build-machine:
    docker:
      - image: circleci/node:10
    working_directory: ~/forge
aliases:
  install_node_modules: &install_node_modules
    run:
      name: Install dependencies
      command: npm install

version: 2.1

jobs:
  test:
    executor: tester
    steps:
      - checkout
      - <<: *install_node_modules
      - run:
          name: Test
          command: npm test
      - run:
          name: Test
          command: npm test
      - run:
          name: E2E Test
          command: npm run test:e2e
      - store_test_results:
          path: ~/forge/reports
      - store_artifacts:
          path: ~/forge/reports

  build:
    executor: node
    steps:
      - checkout
      - <<: *install_node_modules
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  buildOld:
    executor: build-machine
    steps:
      - checkout
      - <<: *install_node_modules
      - run:
          name: Build
          command: npm run build

  deploy:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - <<: *install_node_modules
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - dist
      - run:
          name: Install netlify-cli
          command: sudo npm install -g --silent netlify-cli
      - run:
          name: Deploy to Netlify
          command: netlify deploy --dir=./dist -p

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - buildOld:
          requires:
            - test
  nightly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - "master"
    jobs:
      - test
      - build:
          requires:
            - test
      - buildOld:
          requires:
            - test
  hourly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - "master"
    jobs:
      - test
      - build:
          requires:
            - test
